// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: imports/test_a_1/m1.proto

package test_a_1

import (
	fmt "fmt"
	proto "github.com/temporalio/gogo-protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type E1 int32

const (
	E1_E1_ZERO E1 = 0
)

var E1_name = map[int32]string{
	0: "Zero",
}

var E1_value = map[string]int32{
	"Zero": 0,
}

func (x E1) String() string {
	return proto.EnumName(E1_name, int32(x))
}

func (E1) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c1091de3fa870a14, []int{0}
}

type M1 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M1) Reset()         { *m = M1{} }
func (m *M1) String() string { return proto.CompactTextString(m) }
func (*M1) ProtoMessage()    {}
func (*M1) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1091de3fa870a14, []int{0}
}
func (m *M1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M1.Unmarshal(m, b)
}
func (m *M1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M1.Marshal(b, m, deterministic)
}
func (m *M1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M1.Merge(m, src)
}
func (m *M1) XXX_Size() int {
	return xxx_messageInfo_M1.Size(m)
}
func (m *M1) XXX_DiscardUnknown() {
	xxx_messageInfo_M1.DiscardUnknown(m)
}

var xxx_messageInfo_M1 proto.InternalMessageInfo

type M1_1 struct {
	M1                   *M1      `protobuf:"bytes,1,opt,name=m1,proto3" json:"m1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M1_1) Reset()         { *m = M1_1{} }
func (m *M1_1) String() string { return proto.CompactTextString(m) }
func (*M1_1) ProtoMessage()    {}
func (*M1_1) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1091de3fa870a14, []int{1}
}
func (m *M1_1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M1_1.Unmarshal(m, b)
}
func (m *M1_1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M1_1.Marshal(b, m, deterministic)
}
func (m *M1_1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M1_1.Merge(m, src)
}
func (m *M1_1) XXX_Size() int {
	return xxx_messageInfo_M1_1.Size(m)
}
func (m *M1_1) XXX_DiscardUnknown() {
	xxx_messageInfo_M1_1.DiscardUnknown(m)
}

var xxx_messageInfo_M1_1 proto.InternalMessageInfo

func (m *M1_1) GetM1() *M1 {
	if m != nil {
		return m.M1
	}
	return nil
}

func init() {
	proto.RegisterEnum("test.a.E1", E1_name, E1_value)
	proto.RegisterType((*M1)(nil), "test.a.M1")
	proto.RegisterType((*M1_1)(nil), "test.a.M1_1")
}

func init() { proto.RegisterFile("imports/test_a_1/m1.proto", fileDescriptor_c1091de3fa870a14) }

var fileDescriptor_c1091de3fa870a14 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0x41, 0xeb, 0x82, 0x40,
	0x10, 0x47, 0xff, 0x2e, 0xe2, 0x1f, 0xc6, 0x4b, 0x79, 0xaa, 0x4e, 0xe1, 0x29, 0x02, 0x77, 0x99,
	0xfa, 0x06, 0x81, 0xc7, 0x45, 0xf0, 0xe8, 0x65, 0x59, 0xcd, 0x36, 0xa1, 0x6d, 0x44, 0xc7, 0xef,
	0x1f, 0x6e, 0xb7, 0x6e, 0xc3, 0xfc, 0x1e, 0xbc, 0x07, 0xfb, 0xc1, 0x8f, 0x34, 0xf1, 0xac, 0xb8,
	0x9f, 0xd9, 0x58, 0x83, 0xca, 0xa3, 0x1c, 0x27, 0x62, 0xca, 0x92, 0xf5, 0x25, 0x6d, 0x1e, 0x83,
	0xd0, 0x98, 0xe7, 0x10, 0x6b, 0x34, 0x98, 0x1d, 0x40, 0x78, 0xdc, 0x45, 0xc7, 0xe8, 0x94, 0x5e,
	0x40, 0x7e, 0x11, 0xa9, 0xb1, 0x16, 0x1e, 0xcf, 0x5b, 0x10, 0x25, 0x66, 0x29, 0xfc, 0x97, 0x68,
	0x9a, 0xb2, 0xae, 0x36, 0x7f, 0xb7, 0xaa, 0xd1, 0x6e, 0xe0, 0xe7, 0xd2, 0xca, 0x8e, 0xbc, 0xe2,
	0x7e, 0xb5, 0xd9, 0xd7, 0x40, 0xca, 0x91, 0xa3, 0x22, 0x88, 0xda, 0xe5, 0xa1, 0xc2, 0xd1, 0x15,
	0xae, 0x7f, 0x17, 0xeb, 0x10, 0x6a, 0xee, 0x96, 0xad, 0xfa, 0xcd, 0x6b, 0x93, 0x80, 0x5e, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x79, 0x3c, 0x80, 0xb9, 0x00, 0x00, 0x00,
}
